language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=pypy

script:
  - tox

install:
  # travis wants requirements.txt; we don't, use only 'requires=' in setup.py.
  - if [[ $TRAVIS_PYTHON_VERSION == 2.5 ]] || [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors ordereddict; fi
  - pip install --use-mirrors tox
