language: python

python:
  #- 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  #- 3.4
  #- 3.5
  - pypy

matrix:
  allow_failures:
    # bugs, u'literals'
    - python: 3.2

script:
  - python setup.py develop
  - python setup.py test

install:
  if [[ $TRAVIS_PYTHON_VERSION == 2.5 ]] || [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors ordereddict; fi
