language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
    # not supported ..
  - TOXNENV=py25  # missing
  - TOXNENV=py32  # will fail
  - TOXNENV=py34  # missing
  - TOXNENV=pypy  # will fail

matrix:
  allow_failures:
    - python: 3.2 # bugs, no u'literals'
    - pypy        # a few (minor) bugs ??

script:
  - tox

install:
  # travis wants requirements.txt; we don't, use only 'requires=' in setup.py.
  - if [[ $TRAVIS_PYTHON_VERSION == 2.5 ]] || [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors ordereddict; fi
  - pip install --use-mirrors tox
