language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy

matrix:
  allow_failures:
    - python: 3.2  # Not a new enough 3.2 for blessings
    - python: pypy  # PyPy doesn't have _curses.

script:
  - python setup.py develop
  - python setup.py test

install:
  if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors ordereddict; fi
